### ISSUE TITLE
Suggestions for adding to the README

### ISSUE THREAD

**Issue by ghost** [elicavalheiro/front-end-learning-resources#1]
I suggest adding in REAME.md:

### [YT - Lucas Nhimi](https://www.youtube.com/c/LucasNhimi) - Portuguese | Free Content
> He explains about React and Next features through hands-on videos

### [Fábio Vedovelli - Course](https://javascript.tv.br/) - Portuguese | Paid Content

> Excellent course about applications Javascript testing

**Comment by elicavalheiro** [comment]
Thank's for your suggestions ✨
